//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTENT
    {
        public int PK_SEQ { get; set; }
        public Nullable<int> STT { get; set; }
        public string CONTENT_TEXT { get; set; }
        public Nullable<int> TYPE { get; set; }
        public int GROUP_CONTENT_FK { get; set; }
    }
}
