//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LESSION_TAG
    {
        public int PK_SEQ { get; set; }
        public int LESSON_FK { get; set; }
        public Nullable<int> TAG_FK { get; set; }
    }
}
