//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OOPEZZ_DBEntities : DbContext
    {
        public OOPEZZ_DBEntities()
            : base("name=OOPEZZ_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTENT> CONTENT { get; set; }
        public virtual DbSet<GROUP_CONTENT> GROUP_CONTENT { get; set; }
        public virtual DbSet<LESSION> LESSION { get; set; }
        public virtual DbSet<LESSION_TAG> LESSION_TAG { get; set; }
        public virtual DbSet<PROCESS> PROCESS { get; set; }
        public virtual DbSet<TAG> TAG { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<QUESTION> QUESTION { get; set; }
        public virtual DbSet<ANSWER> ANSWER { get; set; }
        public virtual DbSet<KEYWORD> KEYWORD { get; set; }
    }
}
